package com.trippin.ai.ui.screens.trip

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.automirrored.filled.ArrowForward
import androidx.compose.material.icons.filled.Close
import androidx.compose.material.icons.filled.Lock
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.LinearProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.trippin.ai.data.model.Itinerary
import com.trippin.ai.data.model.ItineraryDay
import com.trippin.ai.data.model.ItineraryStop
import com.trippin.ai.data.model.Proposal
import com.trippin.ai.data.model.TripStatus
import com.trippin.ai.ui.components.EmptyState
import com.trippin.ai.ui.components.Kicker
import com.trippin.ai.ui.components.Panel
import com.trippin.ai.ui.components.RiskPill
import com.trippin.ai.ui.components.SectionTitle
import com.trippin.ai.ui.components.SignalButton
import com.trippin.ai.ui.components.SmallButton
import com.trippin.ai.ui.components.TextInput
import com.trippin.ai.ui.components.clock
import com.trippin.ai.ui.components.dayLabel
import com.trippin.ai.ui.navigation.LocalSnack
import com.trippin.ai.ui.theme.Trip
import com.trippin.intelligence.group.VoteKind

/**
 * The itinerary itself: generated by the genetic algorithm and scored by the Bayesian network, but
 * never silently changed once locked — managers edit directly, everyone else proposes a change.
 */
@Composable
fun PlanTab(vm: TripViewModel, ui: TripUi, onToday: () -> Unit, onLab: () -> Unit, onIdeas: () -> Unit, onPrefs: () -> Unit) {
    val trip = ui.trip ?: return
    val itin = ui.itinerary
    val generation by vm.generation.collectAsStateWithLifecycle()
    val snack = LocalSnack.current
    var whyStop by remember { mutableStateOf<ItineraryStop?>(null) }
    var removeTarget by remember { mutableStateOf<ItineraryStop?>(null) }

    if (itin == null) {
        Column(Modifier.fillMaxSize().padding(20.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) {
            when (val g = generation) {
                is Generation.Running -> Panel {
                    Kicker(g.stage.technique)
                    Text(g.stage.label, style = MaterialTheme.typography.titleLarge)
                    LinearProgressIndicator(Modifier.fillMaxWidth(), color = Trip.Signal, trackColor = Trip.PaperDeep)
                }
                Generation.Idle -> when {
                    trip.status == TripStatus.DECIDING_DESTINATION -> EmptyState(
                        "Pick a destination first",
                        "Once the group decides where to go, generate a day-by-day plan from your ideas and preferences.",
                        action = { SmallButton("Go to ideas & votes", onClick = onIdeas) },
                    )
                    ui.placeIdeas.isEmpty() -> EmptyState(
                        "No places suggested yet",
                        "Add a few ideas so the planner has real places to work with — museums, food, sights.",
                        action = { SmallButton("Suggest places", onClick = onIdeas) },
                    )
                    !vm.canManage -> EmptyState("Waiting on the plan", "An owner or admin needs to generate it. Meanwhile, set your own preferences so it fits you.", action = { SmallButton("Set my preferences", onClick = onPrefs) })
                    else -> Panel {
                        Kicker("Ready when you are")
                        Text("Generate the plan", style = MaterialTheme.typography.headlineSmall)
                        Text("Uses ${ui.placeIdeas.size} suggested places, ${ui.prefsSetCount}/${ui.members.size} members' preferences, real opening hours and the live forecast.", color = Trip.Muted)
                        SignalButton("Generate", onClick = {
                            vm.generate { r -> r.onFailure { snack(it.message ?: "Couldn't generate the plan.") } }
                        })
                    }
                }
            }
        }
        return
    }

    LazyColumn(Modifier.fillMaxSize(), contentPadding = PaddingValues(20.dp, 16.dp, 20.dp, 32.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) {
        item {
            Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween, verticalAlignment = Alignment.CenterVertically) {
                Column {
                    Kicker(if (itin.locked) "Confirmed plan" else "Draft — review before you go")
                    Text("${itin.totalKm.toInt()} km · genetic algorithm improved routing ${itin.gaImprovementPercent.toInt()}%", style = MaterialTheme.typography.bodyMedium, color = Trip.Muted)
                }
                if (itin.locked) Icon(Icons.Filled.Lock, contentDescription = "Locked", tint = Trip.Muted)
            }
        }

        if (ui.pendingProposals.isNotEmpty() && vm.canManage) {
            item {
                SectionTitle("Waiting on your approval (${ui.pendingProposals.size})")
                Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                    ui.pendingProposals.forEach { p -> ProposalRow(p, onApprove = { vm.resolve(p, true) }, onReject = { vm.resolve(p, false) }) }
                }
            }
        }

        itemsIndexed(itin.days) { dayIndex, day ->
            DayCard(
                day = day, dayIndex = dayIndex, itin = itin, vm = vm, ui = ui,
                onWhy = { whyStop = it },
                onRemove = { removeTarget = it },
            )
        }

        if (itin.notes.isNotEmpty()) {
            item {
                SectionTitle("Why it's shaped this way")
                Panel(background = Trip.Card) { itin.notes.forEach { Text("· $it", style = MaterialTheme.typography.bodyMedium) } }
            }
        }

        item {
            Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
                if (!itin.locked) {
                    SmallButton("See the AI Lab", onClick = onLab)
                    if (vm.canManage) SignalButton("Confirm this plan", onClick = { vm.confirmPlan() })
                } else {
                    Row(horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                        SmallButton("Open today", onClick = onToday)
                        if (vm.canManage) SmallButton("Reopen for edits", onClick = { vm.reopenPlan() })
                    }
                }
                if (vm.canManage) SmallButton(if (itin.locked) "Regenerate (unlocks first)" else "Regenerate", onClick = {
                    if (itin.locked) vm.reopenPlan()
                    vm.generate { r -> r.onFailure { snack(it.message ?: "Couldn't regenerate the plan.") } }
                })
            }
        }
    }

    whyStop?.let { s ->
        val day = itin.days.firstOrNull { d -> d.stops.any { it.key == s.key } }
        WhySheet(s, rainKnown = day?.rainKnown ?: false, onDismiss = { whyStop = null }, onLab = { whyStop = null; onLab() })
    }

    removeTarget?.let { s ->
        var reason by remember(s.key) { mutableStateOf("") }
        AlertDialog(
            onDismissRequest = { removeTarget = null },
            title = { Text(if (vm.canManage && !itin.locked) "Remove ${s.name}?" else "Propose removing ${s.name}") },
            text = {
                Column {
                    if (!(vm.canManage && !itin.locked)) Text("The owner or an admin will need to approve this.", color = Trip.Muted, modifier = Modifier.padding(bottom = 8.dp))
                    TextInput(reason, { reason = it }, "Reason (optional)")
                }
            },
            confirmButton = { TextButton(onClick = { vm.removeStop(s, reason); removeTarget = null }) { Text(if (vm.canManage && !itin.locked) "Remove" else "Send proposal", color = Trip.Danger) } },
            dismissButton = { TextButton(onClick = { removeTarget = null }) { Text("Cancel") } },
        )
    }
}

@Composable
private fun DayCard(day: ItineraryDay, dayIndex: Int, itin: Itinerary, vm: TripViewModel, ui: TripUi, onWhy: (ItineraryStop) -> Unit, onRemove: (ItineraryStop) -> Unit) {
    Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween, verticalAlignment = Alignment.CenterVertically) {
            Text("Day ${dayIndex + 1} · ${dayLabel(day.date)}", style = MaterialTheme.typography.titleLarge)
            Text(
                if (day.rainKnown) "${(day.rainProbability * 100).toInt()}% rain · ${day.km.toInt()} km" else "forecast not out yet · ${day.km.toInt()} km",
                style = MaterialTheme.typography.labelMedium, color = Trip.Muted,
            )
        }
        day.stops.forEachIndexed { i, s ->
            StopRow(
                s, canEdit = vm.canContribute,
                canMoveEarlier = dayIndex > 0, canMoveLater = dayIndex < itin.days.size - 1,
                myReaction = ui.reactions[s.key]?.get(vm.me.uid),
                onWhy = { onWhy(s) },
                onReact = { k -> vm.react(s, k) },
                onRemove = { onRemove(s) },
                onMove = { toDay -> vm.moveStop(s, toDay) },
                dayIndex = dayIndex,
            )
            if (i < day.stops.lastIndex) HorizontalDivider(color = Trip.PaperDeep)
        }
    }
}

@Composable
private fun StopRow(
    s: ItineraryStop,
    canEdit: Boolean,
    canMoveEarlier: Boolean,
    canMoveLater: Boolean,
    myReaction: VoteKind?,
    onWhy: () -> Unit,
    onReact: (VoteKind) -> Unit,
    onRemove: () -> Unit,
    onMove: (Int) -> Unit,
    dayIndex: Int,
) {
    Panel(padding = 12.dp, background = if (s.optional) Trip.PaperDeep else Trip.Card) {
        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
            Column(Modifier.weight(1f)) {
                Row {
                    Text(categoryEmoji(s.category) + "  ", style = MaterialTheme.typography.titleMedium)
                    Text(s.name, style = MaterialTheme.typography.titleMedium, maxLines = 1, overflow = TextOverflow.Ellipsis)
                }
                Text("${clock(s.start)}–${clock(s.leave)}" + (if (s.optional) " · optional" else ""), style = MaterialTheme.typography.bodyMedium, color = Trip.Muted)
            }
            RiskPill(s.risk, s.pDisrupted, modifier = Modifier.padding(0.dp))
        }
        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween, verticalAlignment = Alignment.CenterVertically) {
            Row(horizontalArrangement = Arrangement.spacedBy(4.dp)) {
                SmallButton("Why?", onClick = onWhy)
                SmallButton(if (myReaction == VoteKind.UP) "👍 ✓" else "👍", onClick = { onReact(VoteKind.UP) })
                SmallButton(if (myReaction == VoteKind.DOWN) "👎 ✓" else "👎", onClick = { onReact(VoteKind.DOWN) })
            }
            if (canEdit) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    if (canMoveEarlier) IconButton(onClick = { onMove(dayIndex - 1) }) { Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Move to previous day", tint = Trip.Muted) }
                    if (canMoveLater) IconButton(onClick = { onMove(dayIndex + 1) }) { Icon(Icons.AutoMirrored.Filled.ArrowForward, contentDescription = "Move to next day", tint = Trip.Muted) }
                    IconButton(onClick = onRemove) { Icon(Icons.Filled.Close, contentDescription = "Remove", tint = Trip.Danger) }
                }
            }
        }
    }
}

@Composable
private fun ProposalRow(p: Proposal, onApprove: () -> Unit, onReject: () -> Unit) {
    Panel(background = Trip.Card, padding = 14.dp) {
        Text(p.summary, style = MaterialTheme.typography.titleMedium)
        Text("${p.createdByName}" + (if (p.reason.isNotBlank()) " — “${p.reason}”" else ""), color = Trip.Muted, style = MaterialTheme.typography.bodyMedium)
        Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
            SmallButton("Approve", onClick = onApprove, filled = true)
            SmallButton("Decline", onClick = onReject, color = Trip.Danger)
        }
    }
}
