import { z } from 'zod';
import { zodToJsonSchema } from 'zod-to-json-schema';

/**
 * Trippin' AI — Versioned Itinerary Schema (v1)
 * Enforces structured output format generated by LLM and validated by deterministic engine.
 */

export const TimeRegex = /^([01]\d|2[0-3]):[0-5]\d$/; // HH:mm 24-hour format
export const DateRegex = /^\d{4}-\d{2}-\d{2}$/; // YYYY-MM-DD

export const ActivitySchemaV1 = z.object({
  placeId: z.string().min(1, 'Place ID is required'),
  placeName: z.string().min(1, 'Place name is required'),
  activityType: z.enum([
    'ATTRACTION',
    'MUSEUM',
    'RESTAURANT',
    'CAFE',
    'PARK',
    'TRANSIT',
    'HOTEL_CHECKIN',
    'FREE_TIME',
    'NIGHTLIFE'
  ]),
  startTime: z.string().regex(TimeRegex, 'Start time must be formatted as HH:mm (24h)'),
  endTime: z.string().regex(TimeRegex, 'End time must be formatted as HH:mm (24h)'),
  durationMinutes: z.number().int().positive('Duration must be positive minutes'),
  travelTimeFromPreviousMinutes: z.number().int().nonnegative().optional().default(0),
  transitModeFromPrevious: z.enum(['DRIVING', 'WALKING', 'TRANSIT', 'BICYCLING']).optional().default('TRANSIT'),
  estimatedCost: z.number().nonnegative().optional(),
  reason: z.string().min(3, 'Reason for including this activity must be provided'),
  tips: z.string().optional()
});

export type ActivityV1 = z.infer<typeof ActivitySchemaV1>;

export const ItineraryDaySchemaV1 = z.object({
  dayIndex: z.number().int().positive('Day index must be 1-based positive integer'),
  date: z.string().regex(DateRegex, 'Date must be formatted as YYYY-MM-DD'),
  themeSummary: z.string().min(5, 'Theme summary for the day is required'),
  activities: z.array(ActivitySchemaV1).min(1, 'Each day must have at least one scheduled activity')
});

export type ItineraryDayV1 = z.infer<typeof ItineraryDaySchemaV1>;

export const ItinerarySchemaV1 = z.object({
  schemaVersion: z.literal('itinerary.schema.v1').default('itinerary.schema.v1'),
  tripTitle: z.string().min(3, 'Trip title is required'),
  destination: z.string().min(2, 'Destination name is required'),
  summary: z.string().min(10, 'Trip summary is required'),
  totalEstimatedCost: z.number().nonnegative().optional(),
  currency: z.string().length(3).default('USD'),
  days: z.array(ItineraryDaySchemaV1).min(1, 'At least one day must be present')
});

export type ItineraryV1 = z.infer<typeof ItinerarySchemaV1>;

/**
 * OpenAI Structured Output JSON Schema definition for Function Calling / Response Format
 */
export const ItineraryJsonSchemaV1 = zodToJsonSchema(ItinerarySchemaV1 as any, {
  name: 'ItineraryV1'
});

/**
 * Helper to safely parse and validate candidate LLM output
 */
export function validateItineraryV1(input: unknown): {
  success: boolean;
  data?: ItineraryV1;
  errors?: string[];
} {
  const result = ItinerarySchemaV1.safeParse(input);
  if (result.success) {
    return { success: true, data: result.data };
  }
  return {
    success: false,
    errors: result.error.errors.map(
      (err) => `${err.path.join('.')}: ${err.message}`
    )
  };
}
