/**
 * Destination to currency inference.
 *
 * The planner used to default every trip to USD, so a Tokyo or Lisbon trip opened with a
 * dollar budget. This maps the destination a traveller typed to the local currency, and
 * returns null when it genuinely cannot tell, so the UI never invents a currency it does
 * not know. The traveller can always override.
 */

const BY_CITY: Record<string, string> = {
  lisbon: 'EUR',
  porto: 'EUR',
  paris: 'EUR',
  nice: 'EUR',
  lyon: 'EUR',
  marseille: 'EUR',
  rome: 'EUR',
  milan: 'EUR',
  venice: 'EUR',
  florence: 'EUR',
  naples: 'EUR',
  bologna: 'EUR',
  madrid: 'EUR',
  barcelona: 'EUR',
  seville: 'EUR',
  valencia: 'EUR',
  granada: 'EUR',
  berlin: 'EUR',
  munich: 'EUR',
  hamburg: 'EUR',
  cologne: 'EUR',
  frankfurt: 'EUR',
  amsterdam: 'EUR',
  rotterdam: 'EUR',
  brussels: 'EUR',
  bruges: 'EUR',
  vienna: 'EUR',
  salzburg: 'EUR',
  athens: 'EUR',
  santorini: 'EUR',
  dublin: 'EUR',
  helsinki: 'EUR',
  tallinn: 'EUR',
  riga: 'EUR',
  vilnius: 'EUR',
  bratislava: 'EUR',
  ljubljana: 'EUR',
  zagreb: 'EUR',
  split: 'EUR',
  dubrovnik: 'EUR',
  valletta: 'EUR',
  luxembourg: 'EUR',
  nicosia: 'EUR',
  tokyo: 'JPY',
  kyoto: 'JPY',
  osaka: 'JPY',
  sapporo: 'JPY',
  nagoya: 'JPY',
  fukuoka: 'JPY',
  hiroshima: 'JPY',
  okinawa: 'JPY',
  london: 'GBP',
  edinburgh: 'GBP',
  glasgow: 'GBP',
  manchester: 'GBP',
  bristol: 'GBP',
  birmingham: 'GBP',
  cardiff: 'GBP',
  belfast: 'GBP',
  'new york': 'USD',
  'san francisco': 'USD',
  'los angeles': 'USD',
  chicago: 'USD',
  boston: 'USD',
  seattle: 'USD',
  miami: 'USD',
  austin: 'USD',
  denver: 'USD',
  honolulu: 'USD',
  'las vegas': 'USD',
  washington: 'USD',
  zurich: 'CHF',
  geneva: 'CHF',
  lucerne: 'CHF',
  bern: 'CHF',
  stockholm: 'SEK',
  gothenburg: 'SEK',
  oslo: 'NOK',
  bergen: 'NOK',
  copenhagen: 'DKK',
  aarhus: 'DKK',
  reykjavik: 'ISK',
  prague: 'CZK',
  brno: 'CZK',
  budapest: 'HUF',
  warsaw: 'PLN',
  krakow: 'PLN',
  gdansk: 'PLN',
  bucharest: 'RON',
  sofia: 'BGN',
  belgrade: 'RSD',
  istanbul: 'TRY',
  cappadocia: 'TRY',
  antalya: 'TRY',
  moscow: 'RUB',
  kyiv: 'UAH',
  kiev: 'UAH',
  dubai: 'AED',
  'abu dhabi': 'AED',
  'tel aviv': 'ILS',
  jerusalem: 'ILS',
  doha: 'QAR',
  'riyadh': 'SAR',
  'hong kong': 'HKD',
  beijing: 'CNY',
  shanghai: 'CNY',
  shenzhen: 'CNY',
  chengdu: 'CNY',
  taipei: 'TWD',
  seoul: 'KRW',
  busan: 'KRW',
  bangkok: 'THB',
  'chiang mai': 'THB',
  phuket: 'THB',
  hanoi: 'VND',
  'ho chi minh': 'VND',
  'da nang': 'VND',
  singapore: 'SGD',
  'kuala lumpur': 'MYR',
  penang: 'MYR',
  'bali': 'IDR',
  jakarta: 'IDR',
  manila: 'PHP',
  'new delhi': 'INR',
  delhi: 'INR',
  mumbai: 'INR',
  bangalore: 'INR',
  bengaluru: 'INR',
  chennai: 'INR',
  kolkata: 'INR',
  hyderabad: 'INR',
  jaipur: 'INR',
  goa: 'INR',
  colombo: 'LKR',
  kathmandu: 'NPR',
  sydney: 'AUD',
  melbourne: 'AUD',
  brisbane: 'AUD',
  perth: 'AUD',
  auckland: 'NZD',
  queenstown: 'NZD',
  wellington: 'NZD',
  toronto: 'CAD',
  vancouver: 'CAD',
  montreal: 'CAD',
  'quebec city': 'CAD',
  'mexico city': 'MXN',
  cancun: 'MXN',
  'sao paulo': 'BRL',
  'rio de janeiro': 'BRL',
  'buenos aires': 'ARS',
  santiago: 'CLP',
  lima: 'PEN',
  bogota: 'COP',
  'cape town': 'ZAR',
  johannesburg: 'ZAR',
  nairobi: 'KES',
  cairo: 'EGP',
  marrakech: 'MAD',
  'casablanca': 'MAD'
};

const BY_COUNTRY: Record<string, string> = {
  portugal: 'EUR',
  spain: 'EUR',
  france: 'EUR',
  italy: 'EUR',
  germany: 'EUR',
  netherlands: 'EUR',
  belgium: 'EUR',
  austria: 'EUR',
  greece: 'EUR',
  ireland: 'EUR',
  finland: 'EUR',
  estonia: 'EUR',
  latvia: 'EUR',
  lithuania: 'EUR',
  slovakia: 'EUR',
  slovenia: 'EUR',
  croatia: 'EUR',
  malta: 'EUR',
  luxembourg: 'EUR',
  cyprus: 'EUR',
  japan: 'JPY',
  'united kingdom': 'GBP',
  uk: 'GBP',
  england: 'GBP',
  scotland: 'GBP',
  wales: 'GBP',
  'united states': 'USD',
  usa: 'USD',
  'united states of america': 'USD',
  switzerland: 'CHF',
  sweden: 'SEK',
  norway: 'NOK',
  denmark: 'DKK',
  iceland: 'ISK',
  'czech republic': 'CZK',
  czechia: 'CZK',
  hungary: 'HUF',
  poland: 'PLN',
  romania: 'RON',
  bulgaria: 'BGN',
  serbia: 'RSD',
  turkey: 'TRY',
  turkiye: 'TRY',
  russia: 'RUB',
  ukraine: 'UAH',
  'united arab emirates': 'AED',
  uae: 'AED',
  israel: 'ILS',
  qatar: 'QAR',
  'saudi arabia': 'SAR',
  china: 'CNY',
  taiwan: 'TWD',
  'south korea': 'KRW',
  korea: 'KRW',
  thailand: 'THB',
  vietnam: 'VND',
  singapore: 'SGD',
  malaysia: 'MYR',
  indonesia: 'IDR',
  philippines: 'PHP',
  india: 'INR',
  'sri lanka': 'LKR',
  nepal: 'NPR',
  australia: 'AUD',
  'new zealand': 'NZD',
  canada: 'CAD',
  mexico: 'MXN',
  brazil: 'BRL',
  argentina: 'ARS',
  chile: 'CLP',
  peru: 'PEN',
  colombia: 'COP',
  'south africa': 'ZAR',
  kenya: 'KES',
  egypt: 'EGP',
  morocco: 'MAD'
};

/** Currencies the traveller can pick manually, most common first. */
export const SUPPORTED_CURRENCIES = [
  'EUR',
  'USD',
  'GBP',
  'JPY',
  'CHF',
  'SEK',
  'NOK',
  'DKK',
  'PLN',
  'CZK',
  'HUF',
  'TRY',
  'AED',
  'SGD',
  'THB',
  'INR',
  'CNY',
  'HKD',
  'KRW',
  'AUD',
  'NZD',
  'CAD',
  'MXN',
  'BRL',
  'ZAR'
] as const;

function normalize(value: string): string {
  return value
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z\s,]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Returns the local currency for a destination string, or null when it is not recognised.
 * Country names are matched on word boundaries so "Indianapolis" is not read as India.
 */
export function inferCurrency(destination: string): string | null {
  const text = normalize(destination || '');
  if (!text) return null;

  // City match first, exact token against the city list ("Tokyo, Japan" -> tokyo).
  const tokens = text.split(',').map((part) => part.trim()).filter(Boolean);
  for (const token of tokens) {
    if (BY_CITY[token]) return BY_CITY[token];
  }
  for (const [city, code] of Object.entries(BY_CITY)) {
    if (city.includes(' ') && new RegExp(`\\b${city}\\b`).test(text)) return code;
  }

  // Country match on word boundaries, longest names first so "united kingdom" wins over "uk".
  const countries = Object.keys(BY_COUNTRY).sort((a, b) => b.length - a.length);
  for (const country of countries) {
    if (new RegExp(`\\b${country}\\b`).test(text)) return BY_COUNTRY[country];
  }

  return null;
}
